services:
  employee-db:
    image: postgres:18
    environment:
      - POSTGRES_USER=employee_user
      - POSTGRES_PASSWORD=employee_pass
      - POSTGRES_DB=employee_db
    volumes:
      - employee_pgdata:/var/lib/postgresql
    networks:
      - my_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U employee_user -d employee_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-db:
    image: postgres:18
    environment:
      - POSTGRES_USER=auth_user
      - POSTGRES_PASSWORD=auth_pass
      - POSTGRES_DB=auth_db
    volumes:
      - auth_pgdata:/var/lib/postgresql
    networks:
      - my_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_user -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  employee-service: # Serviço de Empregado
    container_name: employee-service
    build:
      context: ./employee
      dockerfile: Dockerfile
    depends_on:
      employee-db:
        condition: service_healthy
    networks:
      - my_network
    env_file:
      - ./employee/.env
    restart: always

  auth-service: # Serviço de Autenticação
    container_name: auth-service
    build:
      context: ./auth
      dockerfile: Dockerfile
    depends_on:
      auth-db:
        condition: service_healthy
    networks:
      - my_network
    env_file:
      - ./auth/.env
    restart: always

  nginx: # Load Balancer
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - employee-service
      - auth-service
    ports:
      - "80:80"
    networks:
      - my_network
    restart: always

networks:
  my_network:
    driver: bridge

volumes:
  employee_pgdata:
  auth_pgdata:
