services:
  employee-db:
    image: postgres:18
    environment:
      - POSTGRES_USER=employee_user
      - POSTGRES_PASSWORD=employee_pass
      - POSTGRES_DB=employee_db
    volumes:
      - employee_pgdata:/var/lib/postgresql
    networks:
      - my_network
    restart: always
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U employee_user -d employee_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  employee-service:
    container_name: employee-service
    build:
      context: ./employee
      dockerfile: Dockerfile
    depends_on:
      employee-db:
        condition: service_healthy
    networks:
      - my_network
    env_file:
      - ./employee/.env
    restart: always

networks:
  my_network:
    driver: bridge

volumes:
  employee_pgdata:
  auth_pgdata:
